name: deployment

on:
  push:
    branches:
      - "feature/deployment"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        run: |
          sudo apt-get update && sudo apt-get install -y python3 git lua5.1
          echo "GIT_VERSION=\"$(git rev-parse HEAD)\" ; GIT_BRANCH=\"$GITHUB_REF_NAME\"" >> vrp/buildinfo.lua
          python3 build/lint.py
          python3 build/buildscript.py --branch $GITHUB_REF_NAME
          python3 build/packAssets.py
          ./build/make_archives.sh
          wget -q -O build/ml_jwt.so https://github.com/eXo-OpenSource/ml_jwt/releases/download/1.0-wip/ml_jwt.so
          wget -q -O build/ml_redis.so https://github.com/eXo-OpenSource/ml_redis/releases/download/1.0-wip/ml_redis.so
      -
        run: |
          docker build -t rl-mta .
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          docker tag rl-mta $GITHUB_REPOSITORY:latest-$(echo $GITHUB_REF_NAME | tr -d /)
          '[ "$GITHUB_REF_NAME" == "master" ] && docker tag rl-mta $GITHUB_REPOSITORY:latest'
          docker push ghcr.io/$GITHUB_REPOSITORY
    
